include:
  - component: $CI_SERVER_FQDN/quiqqer/stabilization/ci-cd-components/quiqqer-package-bundle/quiqqer-package-bundle@main
    inputs:
      php-81: false
      php-82: true
      php-83: true
      php-84: true
      php-85: true

trigger-build-of-docker-images:
  needs:
    - job: release
      artifacts: true
    - job: trigger-update-server-on-protected-branch-push
  stage: deploy
  image: curlimages/curl
  variables:
    RELEASED_VERSION_ARTIFACT: .RELEASED_VERSION.txt
  script:
    - if [ ! -f $RELEASED_VERSION_ARTIFACT ]; then echo "No version released, exiting..."; exit; fi
    - |
      for image_type in production testing demo; do
      # Testing also rebuilds ERP testing because build-dependents is enabled.
      echo "Triggering (re-)build of QUIQQER docker image '$image_type'…"
      curl \
        --fail-with-body \
        --silent \
        --show-error \
        --request POST \
        --form "token=$CI_JOB_TOKEN" \
        --form "ref=main" \
        --form "inputs[image-type]=$image_type" \
        --form "inputs[build-dependents]=true" \
        "${CI_API_V4_URL}/projects/1061/trigger/pipeline" \
        || exit 1
      done
  rules:
    - !reference [release, rules]
